---
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Rozumbunch\Bridge2Cleverreach\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Rozumbunch\Bridge2Cleverreach\Api\ApiManager:
    public: true
  Rozumbunch\Bridge2Cleverreach\Backend\Form\NewsletterGroupsFieldConfiguration:
    public: true
